<a href="https://colab.research.google.com/github/kleber293/calculo_numerico/blob/main/Calculo_Numerico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # $\color{Turquoise}{\text{Binário ⇆ Decimal}}$
#@markdown > $\color{gray}{\text{convert_bxd}}$
def convert_bxd(num, bin=False, dec=False):
    
    def saida(v1, b1, v2, b2):
        print(f'(\033[1;32m{v1}\033[){b1}', end='')
        print(' \u27F6 ', end='')
        print(f'(\033[1;32m{v2}\033[){b2}')

    def dec_inteiro(val):
        bn, bnr, val = list(), str(), int(val)
        bn.append(val % 2)
        while True:
            d = val // 2
            if d == 1 or d == 0:
                bn.append(d)
                break
            bn.append(d % 2)
            val = d
        for x in reversed(bn):
            bnr += str(x)
        return bnr

    conf = num
    
    if bin:
        con = True
        for v in str(num):
            con *= v in '10.'
        if bool(con):
            if isinstance(num, float):
                b, sm = str(num).find('.')-1, 0
                for i in str(num).replace('.', ''):
                    sm += int(i)*2**(b)
                    b -= 1
                saida(conf, '\u2082', sm, '\u2081\u2080')
            else:
                c, s = 0, 0
                for n in str(num):
                    c += 1
                    s += int(n)*2**(len(str(num))-c)
                saida(conf, '\u2082', s, '\u2081\u2080')
        else: 
            print('\033[1;31mO valor digitado não é um número Binário!\033[m')

    elif dec:
        if isinstance(num, float):
            bm, st = list(), str()
            cm = 0 if int(num) == 0 else dec_inteiro(num)
            while True:
                if num > 1:
                    num -= int(num)
                num *= 2
                bm.append(num)
                if num % 1 == 0:
                    break
            for x in bm:
                st += f'{str(int(x))}'
            saida(conf, '\u2081\u2080', f'{cm}.{st}', '\u2082')
        else:
            saida(conf,'\u2081\u2080', dec_inteiro(num), '\u2082')

In [ ]:
#@markdown ### Convertendo um número **Binário** em **Decimal**
Numero_Binario =  10111#@param
convert_bxd(Numero_Binario, bin=True)

(10111[)₂ ⟶ (23[)₁₀


In [ ]:
#@markdown ### Convertendo um número **Decimal** em **Binário**
Numero_Decimal =  13.25#@param
convert_bxd(Numero_Decimal, dec=True)

(13.25[)₁₀ ⟶ (1101.01[)₂


# <HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # $\color{Turquoise}{\text{Método de Gauss}}$
#@markdown > $\color{gray}{\text{eliminacao_gauss}}$

def eliminacao_gauss(hea):
    import numpy as np
    
    arr = np.array(hea, dtype=np.float64, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)

    for cm in range(len(arr[0])-2): # coluna da linha da matriz
        for l, k in zip(range(cm, len(arr)-1), range(len(arr))): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[cm+k+1][cm]
                arr[cm+k+1][c] = v1*arr[cm+k+1][c]-v2*arr[cm][c]
        arr = max_diagonal(arr)

    return arr        

In [ ]:
matriz_para_triangular = [[3, 2, 1, -1, 5], [0, 1, 0, 3, 6], [0, -3, -5, 7, 7], [0, 2, 4, 0, 15]] #@param
#@markdown > $\color{gray}{\text{eliminacao_gauss(matriz_para_triangular)}}$
matriz_triangulada = eliminacao_gauss(matriz_para_triangular)
print(f'\033[32m{matriz_triangulada}'); print()
%timeit eliminacao_gauss(matriz_para_triangular)

[[ 3.0000e+00  2.0000e+00  1.0000e+00 -1.0000e+00  5.0000e+00]
 [ 0.0000e+00 -9.0000e+00 -1.5000e+01  2.1000e+01  2.1000e+01]
 [-0.0000e+00  0.0000e+00  4.5000e+01 -1.4400e+02 -2.2500e+02]
 [-0.0000e+00  0.0000e+00  0.0000e+00 -8.2620e+03 -2.7945e+04]]

1000 loops, best of 5: 731 µs per loop


# <HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # $\color{Turquoise}{\text{Mostrando matriz resultao do Método de Gauss}}$
#@markdown > $\color{gray}{\text{resultado}}$

def resultado(hea):
    '''Entre apenas com uma matriz triangular inferior'''
    import numpy as np
    
    arr = np.array(hea, dtype=np.float64, copy=True); mt = []
    for x in reversed(range(len(arr))):
        n = 0; s = []
        for i, k in zip(range(x+1, len(arr)), range(1, len(arr))):
            s.append(arr[x][i])
            n += s[k-1]*mt[k-1]

        mt.insert(0, (arr[x][len(arr)]-n)/arr.diagonal()[x])

    return mt

In [ ]:
matriz_resultados =  matriz_triangulada#@param
#@markdown > $\color{gray}{\text{resultado(matriz_resultados)}}$
print(f'\033[32mM\u1D40 = {resultado(matriz_resultados)}'); print()
%timeit resultado(matriz_resultados)

Mᵀ = [3.6176470588235285, -4.14705882352941, 5.823529411764706, 3.3823529411764706]

10000 loops, best of 5: 17.5 µs per loop


# <HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # $\color{Turquoise}{\text{Método de Gauss Jordan}}$
#@markdown > $\color{gray}{\text{gauss_jordan}}$

def gauss_jordan(hea):

    import numpy as np

    def simple(arr):
        diag = arr.diagonal()
        for i, x in zip(range(len(diag)), diag):
            arr[i] = arr[i]/x
        return arr

    arr = np.array(hea, dtype=np.float64,  copy=True)

    for _ in range(2): 
        bl = []
        for i, k in zip(arr, range(len(arr))):
            if not k-1 < 0:
                bl.append([i[x] for x in range(k)])
        bl = np.hstack(bl)

        if len(np.where(bl > 0)[0]) != 0:
            arr = eliminacao_gauss(arr)
        else:
            break

    for cm in reversed(range(1, len(arr[0])-1)): # coluna da linha da matriz
        for l, k in zip(reversed(range(cm)), range(1, len(arr))): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[cm-k][cm]

                arr[cm-k][c] = v1*arr[cm-k][c]-v2*arr[cm][c]
            simple(arr)
    return arr

In [ ]:
matriz_para_triangular =  [[3, 2, 1, -1, 5], [0, 1, 0, 3, 6], [0, -3, -5, 7, 7], [0, 2, 4, 0, 15]]#@param
#@markdown > $\color{gray}{\text{gauss_jordan(matriz_para_triangular)}}$
arr = gauss_jordan(matriz_para_triangular)
print(f'\033[32m{arr}'); print()
%timeit gauss_jordan(matriz_para_triangular)

[[ 1.          0.          0.          0.          3.61764706]
 [ 0.          1.          0.          0.         -4.14705882]
 [-0.         -0.          1.         -0.          5.82352941]
 [ 0.         -0.         -0.          1.          3.38235294]]

1000 loops, best of 5: 949 µs per loop


# <HR width=100% color="Turquoise	" align=left noshade>

In [145]:
#@markdown # $\color{Turquoise}{\text{Método de Jacobi}}$
#@markdown > $\color{gray}{\text{m_jacobi}}$

def m_jacobi(hea):

    import numpy as np

    def v(arr, condi, line=0):
        n, rs = [arr[line][-1]], 0
        n.append(
            [x*i for x, i, c in zip(arr[line], condi, range(len(arr[0])))
            if c != line]
        )
        for k in n[1]:
            rs += k
        x = (n[0]-rs)/arr[line][line]
        return x

    arr = np.array(hea, dtype=np.float64, copy=True)

    

In [4]:
import numpy as np

In [36]:
arr = np.array([[10, 2, 1, 7], [1, 5, 1, -8], [2, 3, 10, 6]], dtype=np.float64)
ci = [1, 2, 3]
arr

array([[10.,  2.,  1.,  7.],
       [ 1.,  5.,  1., -8.],
       [ 2.,  3., 10.,  6.]])

In [34]:
n = [arr[0][-1]]
n.append([x*i for x, i in zip(range(3), ci)])
n

[7.0, [0, 0, 0]]

In [49]:
[f'{x}*{i}' for x, i in zip(-1*arr[0], ci)]

['-10.0*1', '-2.0*2', '-1.0*3']

In [139]:
def v(arr, condi, line=0):
    n, rs = [arr[line][-1]], 0
    n.append(
        [x*i for x, i, c in zip(arr[line], condi, range(len(arr[0])))
        if c != line]
    )
    for k in n[1]:
        rs += k
    x = (n[0]-rs)/arr[line][line]
    return x

In [140]:
nv = v(arr, ci, line=0); nv

0.0

In [141]:
nv = v(arr, ci, line=1); nv

-2.4

In [142]:
nv = v(arr, ci, line=2); nv

-0.2

In [128]:
for i in nv[1]:
    print(i)

2.0
6.0


In [98]:
for i, k, l in zip(range(1, 4), range(i), range(2, 5)):
    print(i, k, l)

1 0 2
2 1 3
3 2 4


In [92]:
nv.remove(list(nv[1])[0])

ValueError: ignored

# <HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # $\color{Turquoise}{\text{Contatos}}$
%%html

<table style="white-space: nowrap; width: 0px;" border="0" cellspacing="0">
  <tbody>
    <tr>
      <td style="vertical-align: 0px;">
        <img style="border-right: 3px solid #30D5C8; padding-right: 13px; height: 90px;" src="https://i.pinimg.com/280x280_RS/79/42/c4/7942c414d01e7c8f8c179f905a5a86eb.jpg"/></td>
        <td style="white-space: nowrap; font-family: Helvetica, Arial; padding-left: 11px; font-size: 12px; vertical-align: middle; width: 560px;">
        <h1 style="white-space: nowrap; font-size: 14px; color: #30D5C8; line-height: 1; margin: 0 0 8px 0;">
          <b>CLEBSON DOS SANTOS MARQUES</b>
        </h1>

        <span style="color: #808080; data-contrast: none;">
          Estudante do Curso de Licenciatura em F&iacute;sica pela Universidade Estadual Vale do Acara&uacute;<br />
        </span>
        <span style="white-space: nowrap; font-size: 12px; color: #30D5C8; line-height: 1px; margin: 0 0 8px 0;" data-contrast="none">
          <b>Tel.:</b>
        </span>
        <span style="color: #808080; data-contrast: none;">(88) 9 9412 2413
          <br /><a style="color: #808080; data-contrast: none; text-decoration: none;" href="mailto:klebersantosy@gmail.com">klebersantosy@gmail.com</a><br />
          <a style="color: #808080; data-contrast: none; text-decoration: none;" href="http://lattes.cnpq.br/9411163467458250">http://lattes.cnpq.br/9411163467458250</a>
        </span>

        <div style="white-space: nowrap; margin-top: 8px;">
          <a style="white-space: nowrap; display: inline-block;" href="https://api.whatsapp.com/send?phone=558894122413">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://icon-library.com/images/icon-whatsapp-png/icon-whatsapp-png-2.jpg" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://t.me/clebson_marques">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://www.freepnglogos.com/uploads/telegram-png/telegram-communications-icons-24.png" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://www.passeidireto.com/perfil/371127-klebson-marques/">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://img.utdstc.com/icon/f63/09d/f6309d71c42e9f12c4aaf4800260f4c2ae9637ab4b148c381e8378e80ccce0e6:200" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://github.com/kleber293">
            <img style="white-space: nowrap; width: 26px; height: 20px; object-fit: cover;" src="http://pngimg.com/uploads/github/github_PNG69.png" /></a>
        </div>
      </td>
    </tr>
  </tbody>
</table>