<a href="https://colab.research.google.com/github/kleber293/calculo_numerico/blob/main/Calculo_Numerico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # Binário ⇆ Decimal
def Convert_BxD(num, bin=False, dec=False):
    
    def saida(v1, b1, v2, b2):
        print(f'(\033[1;32m{v1}\033[){b1}', end='')
        print(' \u27F6 ', end='')
        print(f'(\033[1;32m{v2}\033[){b2}')

    def dec_inteiro(val):
        bn, bnr, val = list(), str(), int(val)
        bn.append(val % 2)
        while True:
            d = val // 2
            if d == 1 or d == 0:
                bn.append(d)
                break
            bn.append(d % 2)
            val = d
        for x in reversed(bn):
            bnr += str(x)
        return bnr

    conf = num
    
    if bin:
        con = True
        for v in str(num):
            con *= v in '10.'
        if bool(con):
            if isinstance(num, float):
                b, sm = str(num).find('.')-1, 0
                for i in str(num).replace('.', ''):
                    sm += int(i)*2**(b)
                    b -= 1
                saida(conf, '\u2082', sm, '\u2081\u2080')
            else:
                c, s = 0, 0
                for n in str(num):
                    c += 1
                    s += int(n)*2**(len(str(num))-c)
                saida(conf, '\u2082', s, '\u2081\u2080')
        else: 
            print('\033[1;31mO valor digitado não é um número Binário!\033[m')

    elif dec:
        if isinstance(num, float):
            bm, st = list(), str()
            cm = 0 if int(num) == 0 else dec_inteiro(num)
            while True:
                if num > 1:
                    num -= int(num)
                num *= 2
                bm.append(num)
                if num % 1 == 0:
                    break
            for x in bm:
                st += f'{str(int(x))}'
            saida(conf, '\u2081\u2080', f'{cm}.{st}', '\u2082')
        else:
            saida(conf,'\u2081\u2080', dec_inteiro(num), '\u2082')

In [ ]:
#@markdown ### Convertendo um número **Binário** em **Decimal**
Numero_Binario =  10111#@param
Convert_BxD(Numero_Binario, bin=True)

In [ ]:
#@markdown ### Convertendo um número **Decimal** em **Binário**
Numero_Decimal =  13.25#@param
Convert_BxD(Numero_Decimal, dec=True)

<HR width=100% color="Turquoise	" align=left noshade>

# Método de eliminação de Gauss ou Eliminação Gaussiana

> $\color{gray}{\text{Gauss triângulação }}$

Base: [Aqui](https://www.ufrgs.br/reamat/CalculoNumerico/livro-sci/sdsl-eliminacao_gaussiana.html):

Exercício de texte:

\begin{bmatrix}
1&1&1&1\\
4&4&2&2\\
2&1&-1&0
\end{bmatrix}

<HR width=100% color="Turquoise	" align=left noshade>

# Método de eliminação de Gauss jordan

> $\color{gray}{\text{método do pivotamento parcial}}$

Base: [Aqui](https://www.ufrgs.br/reamat/CalculoNumerico/livro-sci/sdsl-eliminacao_gaussiana.html):

Exercício de texte:

\begin{bmatrix}
2&3&1&-1&6.9\\
-1&1&-4&1&-6.6\\
1&1&1&1&10.2\\
4&-5&1&-2&-12.3
\end{bmatrix}

In [98]:
m = [[2, 3, 1, -1, 6.9],
     [-1, 1, -4, 1, -6.6],
     [1, 1, 1, 1, 10.2],
     [4, -5, 1, -2, -12.3]]

In [99]:
def pivotamento(hea):
    import numpy as np
    
    arr = np.array(hea, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)
    
    return arr

In [100]:
def max_diagonal(arr):

    import numpy as np

    def permutation(arr, shift, end):
        arr = np.insert(arr, end, arr[shift], axis=0)
        finale = shift + 1 if shift > end else shift 
        arr = np.delete(arr, finale, axis=0)
        return arr 

    for i in range(len(arr)):
        arr = permutation(
            arr,
            np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
            i
        )
    return arr

In [175]:
p = pivotamento(m); print(f'\033[34m{p}\033['); print(f'\033[31m{"-="*20}\033[')
print()

for cm in range(len(p[0])-2):
    for l in range(len(p)-1-cm): # linha
        for c in range(len(p[0])): # coluna da linha
            if not c:
                v1, v2 = p[cm][cm], p[l+cm+1][cm]
                sinal = '-'

            # print(f'{v2}*{p[cm][c]} {sinal} {v1}*{p[l+cm+1][c]}, L[{l+cm+1}][{cm}]')
            
            ms = v2*p[cm][c] - v1*p[l+cm+1][c]

            p[l+cm+1][c] = ms

            # print(p, '\n')
        # print(f'\033[31m{"-="*20}\033[')
    # print(f'\033[32m{"*"*20}\033[')

    p = max_diagonal(p)
print(p, '\n')

[[  4.   -5.    1.   -2.  -12.3]
 [  2.    3.    1.   -1.    6.9]
 [ -1.    1.   -4.    1.   -6.6]
 [  1.    1.    1.    1.   10.2]][
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=[

[[ 4.000000e+00 -5.000000e+00  1.000000e+00 -2.000000e+00 -1.230000e+01]
 [ 0.000000e+00 -2.200000e+01 -2.000000e+00  0.000000e+00 -5.220000e+01]
 [ 0.000000e+00  0.000000e+00  3.280000e+02 -4.400000e+01  7.992000e+02]
 [-0.000000e+00 -0.000000e+00  0.000000e+00  4.540800e+04  1.907136e+05]] 

