<a href="https://colab.research.google.com/github/kleber293/calculo_numerico/blob/main/Calculo_Numerico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<HR width=100% color="Turquoise	" align=left noshade>

In [ ]:
#@markdown # Binário ⇆ Decimal
def Convert_BxD(num, bin=False, dec=False):
    
    def saida(v1, b1, v2, b2):
        print(f'(\033[1;32m{v1}\033[){b1}', end='')
        print(' \u27F6 ', end='')
        print(f'(\033[1;32m{v2}\033[){b2}')

    def dec_inteiro(val):
        bn, bnr, val = list(), str(), int(val)
        bn.append(val % 2)
        while True:
            d = val // 2
            if d == 1 or d == 0:
                bn.append(d)
                break
            bn.append(d % 2)
            val = d
        for x in reversed(bn):
            bnr += str(x)
        return bnr

    conf = num
    
    if bin:
        con = True
        for v in str(num):
            con *= v in '10.'
        if bool(con):
            if isinstance(num, float):
                b, sm = str(num).find('.')-1, 0
                for i in str(num).replace('.', ''):
                    sm += int(i)*2**(b)
                    b -= 1
                saida(conf, '\u2082', sm, '\u2081\u2080')
            else:
                c, s = 0, 0
                for n in str(num):
                    c += 1
                    s += int(n)*2**(len(str(num))-c)
                saida(conf, '\u2082', s, '\u2081\u2080')
        else: 
            print('\033[1;31mO valor digitado não é um número Binário!\033[m')

    elif dec:
        if isinstance(num, float):
            bm, st = list(), str()
            cm = 0 if int(num) == 0 else dec_inteiro(num)
            while True:
                if num > 1:
                    num -= int(num)
                num *= 2
                bm.append(num)
                if num % 1 == 0:
                    break
            for x in bm:
                st += f'{str(int(x))}'
            saida(conf, '\u2081\u2080', f'{cm}.{st}', '\u2082')
        else:
            saida(conf,'\u2081\u2080', dec_inteiro(num), '\u2082')

In [ ]:
#@markdown ### Convertendo um número **Binário** em **Decimal**
Numero_Binario =  10111#@param
Convert_BxD(Numero_Binario, bin=True)

(10111[)₂ ⟶ (23[)₁₀


In [ ]:
#@markdown ### Convertendo um número **Decimal** em **Binário**
Numero_Decimal =  13.25#@param
Convert_BxD(Numero_Decimal, dec=True)

(13.25[)₁₀ ⟶ (1101.01[)₂


<HR width=100% color="Turquoise	" align=left noshade>

# Método de eliminação de Gauss ou Eliminação Gaussiana

> $\color{gray}{\text{Gauss triângulação }}$

Base: [Aqui](https://www.ufrgs.br/reamat/CalculoNumerico/livro-sci/sdsl-eliminacao_gaussiana.html):

Exercício de texte:

\begin{bmatrix}
1&1&1&1\\
4&4&2&2\\
2&1&-1&0
\end{bmatrix}

<HR width=100% color="Turquoise	" align=left noshade>

# Método de eliminação de Gauss jordan

> $\color{gray}{\text{método do pivotamento parcial}}$

Base: [Aqui](https://www.ufrgs.br/reamat/CalculoNumerico/livro-sci/sdsl-eliminacao_gaussiana.html):

Exercício de texte:

\begin{bmatrix}
1&1&1&1\\
4&4&2&2\\
2&1&-1&0
\end{bmatrix}

In [466]:
m = [[1, 1, 1, 1],
     [4, 4, 2, 2],
     [2, 1, -1, 0]]

In [471]:
def pivotamento(hea):
    import numpy as np
    
    arr = np.array(hea, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)
    
    print(arr)

In [472]:
print(m, '\n')

pivotamento(m)

[[1, 1, 1, 1], [4, 4, 2, 2], [2, 1, -1, 0]] 

[[ 4  4  2  2]
 [ 1  1  1  1]
 [ 2  1 -1  0]]
