<a href="https://colab.research.google.com/github/kleber293/calculo_numerico/blob/main/Calculo_Numerico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<HR width=100% color="Turquoise	" align=left noshade>

In [35]:
#@markdown # Binário ⇆ Decimal
def Convert_BxD(num, bin=False, dec=False):
    
    def saida(v1, b1, v2, b2):
        print(f'(\033[1;32m{v1}\033[){b1}', end='')
        print(' \u27F6 ', end='')
        print(f'(\033[1;32m{v2}\033[){b2}')

    def dec_inteiro(val):
        bn, bnr, val = list(), str(), int(val)
        bn.append(val % 2)
        while True:
            d = val // 2
            if d == 1 or d == 0:
                bn.append(d)
                break
            bn.append(d % 2)
            val = d
        for x in reversed(bn):
            bnr += str(x)
        return bnr

    conf = num
    
    if bin:
        con = True
        for v in str(num):
            con *= v in '10.'
        if bool(con):
            if isinstance(num, float):
                b, sm = str(num).find('.')-1, 0
                for i in str(num).replace('.', ''):
                    sm += int(i)*2**(b)
                    b -= 1
                saida(conf, '\u2082', sm, '\u2081\u2080')
            else:
                c, s = 0, 0
                for n in str(num):
                    c += 1
                    s += int(n)*2**(len(str(num))-c)
                saida(conf, '\u2082', s, '\u2081\u2080')
        else: 
            print('\033[1;31mO valor digitado não é um número Binário!\033[m')

    elif dec:
        if isinstance(num, float):
            bm, st = list(), str()
            cm = 0 if int(num) == 0 else dec_inteiro(num)
            while True:
                if num > 1:
                    num -= int(num)
                num *= 2
                bm.append(num)
                if num % 1 == 0:
                    break
            for x in bm:
                st += f'{str(int(x))}'
            saida(conf, '\u2081\u2080', f'{cm}.{st}', '\u2082')
        else:
            saida(conf,'\u2081\u2080', dec_inteiro(num), '\u2082')

In [36]:
#@markdown ### Convertendo um número **Binário** em **Decimal**
Numero_Binario =  10111#@param
Convert_BxD(Numero_Binario, bin=True)

(10111[)₂ ⟶ (23[)₁₀


In [37]:
#@markdown ### Convertendo um número **Decimal** em **Binário**
Numero_Decimal =  13.25#@param
Convert_BxD(Numero_Decimal, dec=True)

(13.25[)₁₀ ⟶ (1101.01[)₂


<HR width=100% color="Turquoise	" align=left noshade>

In [38]:
#@markdown # Método de eliminação de Gauss ou Eliminação Gaussiana
#@markdown > $\color{gray}{\text{Gauss triângulação }}$

def eliminacao_gauss(hea):
    import numpy as np
    
    arr = np.array(hea, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)

    for cm in range(len(arr[0])-2): # coluna da linha da matriz
        for l in range(len(arr)-1-cm): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[l+cm+1][cm]

                ms = v2*arr[cm][c] - v1*arr[l+cm+1][c]

                arr[l+cm+1][c] = ms

        arr = max_diagonal(arr)
    return arr        

In [78]:
m1 = [[1, 1, 1, 1], [4, 4, 2, 2], [2, 1, -1, 0]] #@param

In [79]:
#@markdown # Mostrando resultados de uma matriz triângular
def resultado(arr):
    '''Entre apenas com uma matriz triangular inferior'''
    c, l = len(arr), len(arr[0])
    
    for x in range(1, len(arr)+1):
        m1[len(m1)-x][len(m1)]/m1[len(m1)-1][len(m1)-x]

    msg = f'M\u1D40 = {_}'

    return msg 

In [191]:
import numpy as np

mm = np.array([[1, 2,  3,  4],[0, 5,  6,  7],[0, 0, 8, 9]])
for i, k in zip(range(len(mm)), mm):
    print(i, k)

0 [1 2 3 4]
1 [0 5 6 7]
2 [0 0 8 9]


In [192]:
print(len(mm)-1, len(mm[0])-1)

2 3


In [193]:
mt = [mm[len(mm)-1][len(mm[0])-1]/mm.diagonal()[-1]]
for x in range(len(mm)-1, -1, -1):
    s = []; print(f"\033[35m{x}\033[")
    for i in range(x+1, len(mm)):        
        s.append(mm[x][i])
    print(s)

2[
[]
1[
[6]
0[
[2, 3]


<HR width=100% color="Turquoise	" align=left noshade>

# Método de eliminação de Gauss jordan

> $\color{gray}{\text{método do pivotamento parcial}}$


Exercício de texte:

\begin{bmatrix}
2&3&1&-1&6.9\\
-1&1&-4&1&-6.6\\
1&1&1&1&10.2\\
4&-5&1&-2&-12.3
\end{bmatrix}

In [46]:
m2 = [[2, 3, 1, -1, 6.9],
      [-1, 1, -4, 1, -6.6],
      [1, 1, 1, 1, 10.2],
      [4, -5, 1, -2, -12.3]]

def gauss_jordan(hea):
    import numpy as np
    
    arr = np.array(hea, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)

    for cm in range(len(arr[0])-2): # coluna da linha da matriz
        for l in range(len(arr)-1-cm): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[l+cm+1][cm]

                ms = v2*arr[cm][c] - v1*arr[l+cm+1][c]

                arr[l+cm+1][c] = ms

        arr = max_diagonal(arr)
    return arr

print(gauss_jordan(m2))

[[ 4.000000e+00 -5.000000e+00  1.000000e+00 -2.000000e+00 -1.230000e+01]
 [ 0.000000e+00 -2.200000e+01 -2.000000e+00  0.000000e+00 -5.220000e+01]
 [ 0.000000e+00  0.000000e+00  3.280000e+02 -4.400000e+01  7.992000e+02]
 [-0.000000e+00 -0.000000e+00  0.000000e+00  4.540800e+04  1.907136e+05]]


<HR width=100% color="Turquoise	" align=left noshade>
<p><h1><font color="Turquoise">Contatos</font><h1></p>

In [47]:
#@title
%%html

<table style="white-space: nowrap; width: 0px;" border="0" cellspacing="0">
  <tbody>
    <tr>
      <td style="vertical-align: 0px;">
        <img style="border-right: 3px solid #30D5C8; padding-right: 13px; height: 90px;" src="https://i.pinimg.com/280x280_RS/79/42/c4/7942c414d01e7c8f8c179f905a5a86eb.jpg"/></td>
        <td style="white-space: nowrap; font-family: Helvetica, Arial; padding-left: 11px; font-size: 12px; vertical-align: middle; width: 560px;">
        <h1 style="white-space: nowrap; font-size: 14px; color: #30D5C8; line-height: 1; margin: 0 0 8px 0;">
          <b>CLEBSON DOS SANTOS MARQUES</b>
        </h1>

        <span style="color: #808080; data-contrast: none;">
          Estudante do Curso de Licenciatura em F&iacute;sica pela Universidade Estadual Vale do Acara&uacute;<br />
        </span>
        <span style="white-space: nowrap; font-size: 12px; color: #30D5C8; line-height: 1px; margin: 0 0 8px 0;" data-contrast="none">
          <b>Tel.:</b>
        </span>
        <span style="color: #808080; data-contrast: none;">(88) 9 9412 2413
          <br /><a style="color: #808080; data-contrast: none; text-decoration: none;" href="mailto:klebersantosy@gmail.com">klebersantosy@gmail.com</a><br />
          <a style="color: #808080; data-contrast: none; text-decoration: none;" href="http://lattes.cnpq.br/9411163467458250">http://lattes.cnpq.br/9411163467458250</a>
        </span>

        <div style="white-space: nowrap; margin-top: 8px;">
          <a style="white-space: nowrap; display: inline-block;" href="https://api.whatsapp.com/send?phone=558894122413">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://icon-library.com/images/icon-whatsapp-png/icon-whatsapp-png-2.jpg" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://t.me/clebson_marques">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://www.freepnglogos.com/uploads/telegram-png/telegram-communications-icons-24.png" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://www.passeidireto.com/perfil/371127-klebson-marques/">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://img.utdstc.com/icon/f63/09d/f6309d71c42e9f12c4aaf4800260f4c2ae9637ab4b148c381e8378e80ccce0e6:200" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://github.com/kleber293">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://toppng.com/uploads/preview/octocat-filled-icon-github-icon-svg-11553443886f4krecogcv.png" /></a>
        </div>
      </td>
    </tr>
  </tbody>
</table>