<a href="https://colab.research.google.com/github/kleber293/calculo_numerico/blob/main/Calculo_Numerico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <HR width=100% color="Turquoise	" align=left noshade>

In [545]:
#@markdown # $\color{Turquoise}{\text{Binário ⇆ Decimal}}$
#@markdown > $\color{gray}{\text{convert_bxd}}$
def convert_bxd(num, bin=False, dec=False):
    
    def saida(v1, b1, v2, b2):
        print(f'(\033[1;32m{v1}\033[){b1}', end='')
        print(' \u27F6 ', end='')
        print(f'(\033[1;32m{v2}\033[){b2}')

    def dec_inteiro(val):
        bn, bnr, val = list(), str(), int(val)
        bn.append(val % 2)
        while True:
            d = val // 2
            if d == 1 or d == 0:
                bn.append(d)
                break
            bn.append(d % 2)
            val = d
        for x in reversed(bn):
            bnr += str(x)
        return bnr

    conf = num
    
    if bin:
        con = True
        for v in str(num):
            con *= v in '10.'
        if bool(con):
            if isinstance(num, float):
                b, sm = str(num).find('.')-1, 0
                for i in str(num).replace('.', ''):
                    sm += int(i)*2**(b)
                    b -= 1
                saida(conf, '\u2082', sm, '\u2081\u2080')
            else:
                c, s = 0, 0
                for n in str(num):
                    c += 1
                    s += int(n)*2**(len(str(num))-c)
                saida(conf, '\u2082', s, '\u2081\u2080')
        else: 
            print('\033[1;31mO valor digitado não é um número Binário!\033[m')

    elif dec:
        if isinstance(num, float):
            bm, st = list(), str()
            cm = 0 if int(num) == 0 else dec_inteiro(num)
            while True:
                if num > 1:
                    num -= int(num)
                num *= 2
                bm.append(num)
                if num % 1 == 0:
                    break
            for x in bm:
                st += f'{str(int(x))}'
            saida(conf, '\u2081\u2080', f'{cm}.{st}', '\u2082')
        else:
            saida(conf,'\u2081\u2080', dec_inteiro(num), '\u2082')

In [546]:
#@markdown ### Convertendo um número **Binário** em **Decimal**
Numero_Binario =  10111#@param
convert_bxd(Numero_Binario, bin=True)

(10111[)₂ ⟶ (23[)₁₀


In [547]:
#@markdown ### Convertendo um número **Decimal** em **Binário**
Numero_Decimal =  13.25#@param
convert_bxd(Numero_Decimal, dec=True)

(13.25[)₁₀ ⟶ (1101.01[)₂


# <HR width=100% color="Turquoise	" align=left noshade>

In [574]:
#@markdown # $\color{Turquoise}{\text{Método de eliminação gaussiana}}$
#@markdown > $\color{gray}{\text{eliminacao_gauss}}$

def eliminacao_gauss(hea):
    import numpy as np
    
    arr = np.array(hea, copy=True)
    
    def max_diagonal(arr):
        
        def permutation(arr, shift, end):
            arr = np.insert(arr, end, arr[shift], axis=0)
            finale = shift + 1 if shift > end else shift 
            arr = np.delete(arr, finale, axis=0)
            return arr 

        for i in range(len(arr)):
            arr = permutation(
                arr,
                np.where(arr[i:, i] == max(arr[i:, i], key=abs))[0][0] + i,
                i
            )
        return arr

    arr = max_diagonal(arr)

    for cm in range(len(arr[0])-2): # coluna da linha da matriz
        for l, k in zip(range(cm, len(arr)-1), range(len(arr))): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[cm+k+1][cm]
                arr[cm+k+1][c] = v1*arr[cm+k+1][c]-v2*arr[cm][c]
        arr = max_diagonal(arr)

    return arr        

In [575]:
Matriz_para_Triangular = [[2, 1, 1, 1, 1], [1, 2, 1, 1, 2], [1, 1, 2, 1, 3], [1, 1, 1, 2, 4]] #@param
#@markdown > $\color{gray}{\text{Matriz_Triangulada}}$
Matriz_Triangulada = eliminacao_gauss(Matriz_para_Triangular)
print(f'\033[32m{Matriz_Triangulada}')

[[  2   1   1   1   1]
 [  0   3   1   1   3]
 [  0   0   8   2  12]
 [  0   0   0  60 120]]


# <HR width=100% color="Turquoise	" align=left noshade>

In [577]:
#@markdown # $\color{Turquoise}{\text{Mostrando resultados de uma matriz triângular}}$
#@markdown > $\color{gray}{\text{resultado}}$

def resultado(hea):
    '''Entre apenas com uma matriz triangular inferior'''
    import numpy as np
    
    arr = np.array(hea, copy=True); mt = []
    for x in reversed(range(len(arr))):
        n = 0; s = []
        for i, k in zip(range(x+1, len(arr)), range(1, len(arr))):
            s.append(arr[x][i])
            n += s[k-1]*mt[k-1]

        mt.insert(0, (arr[x][len(arr)]-n)/arr.diagonal()[x])

    return mt

In [551]:
Matriz_Resultados =  Matriz_Triangulada#@param
print(f'\033[32mM\u1D40 = {resultado(Matriz_Resultados)}')

Mᵀ = [-1.0, -0.0, 1.0, 2.0]


# <HR width=100% color="Turquoise	" align=left noshade>

In [714]:
#@markdown # $\color{Turquoise}{\text{Método de Gauss Jordan}}$
#@markdown > $\color{gray}{\text{gauss_jordan}}$

def gauss_jordan(hea):

    import numpy as np
    
    arr = np.array(hea, copy=True)

    for _ in range(2): 
        bl = []
        for i, k in zip(arr, range(len(arr))):
            if not k-1 < 0:
                bl.append([i[x] for x in range(k)])
        bl = np.hstack(bl)

        if len(np.where(bl > 0)[0]) != 0:
            arr = eliminacao_gauss(arr)
        else:
            break

    for cm in reversed(range(1, len(arr[0])-1)): # coluna da linha da matriz
        for l, k in zip(reversed(range(cm)), range(1, len(arr))): # linha
            for c in range(len(arr[0])): # coluna da linha
                if not c:
                    v1, v2 = arr[cm][cm], arr[cm-k][cm]

                arr[cm-k][c] = v1*arr[cm-k][c]-v2*arr[cm][c]

    diag = arr.diagonal()
    for i, x in zip(range(len(diag)), diag):
        arr[i] = arr[i]/x
    
    return arr

In [715]:
Matriz_para_Triangular = [[2, 1, 1, 1, 1], [1, 2, 1, 1, 2], [1, 1, 2, 1, 3], [1, 1, 1, 2, 4]] #@param
#@markdown > $\color{gray}{\text{arr}}$
arr = eliminacao_gauss(Matriz_para_Triangular)
print(f'\033[32m{arr}')

[[  2   1   1   1   1]
 [  0   3   1   1   3]
 [  0   0   8   2  12]
 [  0   0   0  60 120]]


In [716]:
gauss_jordan(arr)

array([[ 1,  0,  0,  0, -1],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  0,  1,  2]])

# <HR width=100% color="Turquoise	" align=left noshade>

In [559]:
#@markdown # $\color{Turquoise}{\text{Contatos}}$
%%html

<table style="white-space: nowrap; width: 0px;" border="0" cellspacing="0">
  <tbody>
    <tr>
      <td style="vertical-align: 0px;">
        <img style="border-right: 3px solid #30D5C8; padding-right: 13px; height: 90px;" src="https://i.pinimg.com/280x280_RS/79/42/c4/7942c414d01e7c8f8c179f905a5a86eb.jpg"/></td>
        <td style="white-space: nowrap; font-family: Helvetica, Arial; padding-left: 11px; font-size: 12px; vertical-align: middle; width: 560px;">
        <h1 style="white-space: nowrap; font-size: 14px; color: #30D5C8; line-height: 1; margin: 0 0 8px 0;">
          <b>CLEBSON DOS SANTOS MARQUES</b>
        </h1>

        <span style="color: #808080; data-contrast: none;">
          Estudante do Curso de Licenciatura em F&iacute;sica pela Universidade Estadual Vale do Acara&uacute;<br />
        </span>
        <span style="white-space: nowrap; font-size: 12px; color: #30D5C8; line-height: 1px; margin: 0 0 8px 0;" data-contrast="none">
          <b>Tel.:</b>
        </span>
        <span style="color: #808080; data-contrast: none;">(88) 9 9412 2413
          <br /><a style="color: #808080; data-contrast: none; text-decoration: none;" href="mailto:klebersantosy@gmail.com">klebersantosy@gmail.com</a><br />
          <a style="color: #808080; data-contrast: none; text-decoration: none;" href="http://lattes.cnpq.br/9411163467458250">http://lattes.cnpq.br/9411163467458250</a>
        </span>

        <div style="white-space: nowrap; margin-top: 8px;">
          <a style="white-space: nowrap; display: inline-block;" href="https://api.whatsapp.com/send?phone=558894122413">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://icon-library.com/images/icon-whatsapp-png/icon-whatsapp-png-2.jpg" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://t.me/clebson_marques">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://www.freepnglogos.com/uploads/telegram-png/telegram-communications-icons-24.png" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://www.passeidireto.com/perfil/371127-klebson-marques/">
            <img style="white-space: nowrap; width: 20px; height: 20px;" src="https://img.utdstc.com/icon/f63/09d/f6309d71c42e9f12c4aaf4800260f4c2ae9637ab4b148c381e8378e80ccce0e6:200" />
          </a> <a style="white-space: nowrap; display: inline-block;" href="https://github.com/kleber293">
            <img style="white-space: nowrap; width: 26px; height: 20px; object-fit: cover;" src="http://pngimg.com/uploads/github/github_PNG69.png" /></a>
        </div>
      </td>
    </tr>
  </tbody>
</table>